excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
line_length: 200
disabled_rules:
  - trailing_whitespace
  - force_cast
identifier_name:
  max_length:
    warning: 50
  min_length: # only min_length
    error: 0
    warning: 0